name: nuget-api-dataget
author: chrdek
description: Github Action returning an xml or json response from NuGet Api (APIv2, v3) by using NuGet owner's name and stores the result in a predefined Gist in Base64.
inputs:
  ownerName:
    description: string, nuget api registry username
    required: true
  isXmlResp:
    description: string, can be only TRUE or FALSE
    required: true
  GIST_ID:
    description: string, identifier of the Gist that was created to store the xml or json response in
    required: true
  ACTION_TOKEN:
    description: string, PAT token to be used in Github API for updating the Gist
    required: true


outputs:
   xml:
     description: raw xml response encoded as base64
   json:
     description: raw json response encoded as base64

runs:
  using: 'ubuntu-latest'
  main: '.github/workflows/nugetapi_update.yml'
branding:
  icon: 'watch'
  color: 'blue'

